=== jodi-one/jodi/jodi_core/src/main/resources/jodi-packages.v1.1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:ext="http://jodi.one/etlmodel/extensions"
           xmlns:jaxb="http://java.sun.com/xml/ns/jaxb"
           jaxb:version="2.1">

    <xs:import namespace="http://jodi.one/etlmodel/extensions"
               schemaLocation="jodi-packages-extensions.v1.1.xsd"/>

    <xs:element name="Packages">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Package" maxOccurs="unbounded"/>
                <xs:element name="extension" type="ext:PackagesExtension" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Package">
        <xs:complexType>
            <xs:all>
                <xs:element name="Comments" type="xs:string" minOccurs="0"/>
                <xs:element name="FolderCode" type="xs:string"/>
                <xs:element name="PackageName" type="xs:string"/>
                <xs:element name="PackageListItem" type="xs:string"/>
                <xs:element name="Before" type="Steps" minOccurs="0"/>
                <xs:element name="After" type="Steps" minOccurs="0"/>
                <xs:element name="GotoOnFinalSuccess" type="xs:string" minOccurs="0"/>
                <xs:element name="Failure" type="Steps" minOccurs="0"/>
                <xs:element name="extension" type="ext:PackageExtension" minOccurs="0"/>
            </xs:all>
        </xs:complexType>
    </xs:element>

    <!-- Steps defines abstract type which is the base for multiple sub-types.
        It uses the substitution type to allow that a list of steps can have different
        sub-types. Sub-types are defined with the extension feature, which forces
        the creation of classes that inherit from the Step class. -->
    <xs:complexType name="Steps">
        <xs:sequence>
            <xs:element ref="Step" maxOccurs="unbounded"/>
            <xs:element name="extension" type="ext:StepsExtension" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="Step" type="StepType" abstract="true"/>
    <xs:complexType name="StepType">
        <xs:sequence>
            <xs:element name="Name" type="xs:string"/>
            <xs:element name="Label" type="xs:string" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="Variable" type="VariableType" substitutionGroup="Step"/>

    <xs:element name="ExecPackage" type="ExecPackageType" substitutionGroup="Step"/>
    <xs:complexType name="ExecPackageType">
        <xs:complexContent>
            <xs:extension base="StepType">
                <xs:sequence>
                    <xs:element name="Asynchronous" type="xs:boolean" minOccurs="0"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:element name="ExecProcedure" type="ExecProcedureType" substitutionGroup="Step"/>
    <xs:complexType name="ExecProcedureType">
        <xs:complexContent>
            <xs:extension base="StepType">
                <xs:sequence>
                    <xs:element ref="Parameters" minOccurs="0"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:element name="Parameters">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Parameter" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Parameter">
        <xs:complexType>
            <xs:all>
                <xs:element name="Name" type="xs:string"/>
                <xs:element name="Value" type="xs:string"/>
            </xs:all>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="VariableTypeCodeEnum">
        <xs:restriction base="xs:string">
            <xs:enumeration value="REFRESH"/>
            <xs:enumeration value="EVALUATE"/>
            <xs:enumeration value="SET"/>
            <xs:enumeration value="DECLARE"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="SetOperatorEnum">
        <xs:restriction base="xs:string">
            <xs:enumeration value="ASSIGN"/>
            <xs:enumeration value="INCREMENT"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="ExecCommand" type="ExecCommandType" substitutionGroup="Step"/>
    <xs:complexType name="ExecCommandType">
        <xs:complexContent>
            <xs:extension base="StepType">
                <xs:sequence>
                    <xs:element ref="Parameters" minOccurs="0"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>


    <xs:element name="ModelCommand" type="ModelType" substitutionGroup="Step"/>
    <xs:complexType name="ModelType">
        <xs:complexContent>
            <xs:extension base="StepType">
                <xs:sequence>
                    <xs:element name="Model" type="xs:string"/>
                    <xs:element name="ActionType" type="ModelTypeActionEnum"/>
                    <xs:element name="CreateSubscribers" type="xs:boolean" minOccurs="0"/>
                    <xs:element name="DropSubscribers" type="xs:boolean" minOccurs="0"/>
                    <xs:element name="InstallJournalization" type="xs:boolean" minOccurs="0"/>
                    <xs:element name="UninstallJournalization" type="xs:boolean" minOccurs="0"/>
                    <xs:element name="Subscriber" type="xs:string" minOccurs="0"/>
                    <xs:element name="ExtendWindow" type="xs:boolean" minOccurs="0"/>
                    <xs:element name="PurgeJournal" type="xs:boolean" minOccurs="0"/>
                    <xs:element name="LockSubscribers" type="xs:boolean" minOccurs="0"/>
                    <xs:element name="UnlockSubscribers" type="xs:boolean" minOccurs="0"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:simpleType name="ModelTypeActionEnum">
        <xs:restriction base="xs:string">
            <xs:enumeration value="CONTROL"/>
            <xs:enumeration value="JOURNALIZE"/>
            <xs:enumeration value="REVERSE_ENGINEER"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="VariableType">
        <xs:complexContent>
            <xs:extension base="StepType">
                <xs:sequence>
                    <xs:element name="Type" type="VariableTypeCodeEnum"/>
                    <xs:element name="Operator" type="xs:string" minOccurs="0"/>
                    <xs:element name="SetOperator" type="SetOperatorEnum" minOccurs="0"/>
                    <xs:element name="Value" type="xs:string" minOccurs="0"/>
                    <xs:element name="IncrementBy" type="xs:int" minOccurs="0"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

</xs:schema>

=== jodi-one/jodi/jodi_qa/src/test/resources/FunctionalTest/xml/IKM_SQL_TO_FILE_APPEND_2S/0.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<Packages xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:noNamespaceSchemaLocation="../../../../../../../jodi_core/src/main/resources/jodi-packages.v1.1.xsd">
  
    <Package>
      <FolderCode>BulkLoadFILE_DWH_SRC</FolderCode>
      <PackageName>IKM_SQL_TO_FILE_APPEND_2S</PackageName>
      <PackageListItem>IKM_SQL_TO_FILE_APPEND_2S</PackageListItem>
     <After>
      <ExecProcedure><Name>DeleteCountryList</Name></ExecProcedure>
      </After>
     </Package>
  
 </Packages>

=== jodi-one/jodi/jodi_qa/src/test/resources/SampleC/xml/100_DWH_CON_CHINOOK/0.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<Packages xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../../../../../../jodi_core/src/main/resources/jodi-packages.v1.1.xsd">
	<Package>
		<FolderCode>InitialORACLE_DWH_CON_CHINOOK</FolderCode>
		<PackageName>INITIALDWH_CON_CHINOOK</PackageName>
		<PackageListItem>PACKAGE_ALL</PackageListItem>
		<Before>
			<Variable>
				<Name>LOAD_UP_TO_DATE</Name>
	      		<Type>DECLARE</Type>
			</Variable>
			<Variable>
				<Name>LOAD_UP_TO_DATE</Name>
				<Type>REFRESH</Type>
			</Variable>
		</Before>
  </Package>
	<Package>
		<PackageName>TEST_MKDIR</PackageName>
		<FolderCode>InitialORACLE_DWH_CON_CHINOOK</FolderCode>
		<PackageListItem>PACKAGE_ALL</PackageListItem>
		<Before>
			<ExecCommand>
				<Name>OdiMkDir</Name>
				<Parameters>
					<Parameter>
						<Name>DIR</Name>
						<Value>/tmp/mkDir</Value>
					</Parameter>
				</Parameters>
			</ExecCommand>
		</Before>
	</Package>
</Packages>

=== jodi-one/jodi/jodi_qa/src/test/resources/FunctionalTest/xml/Trans_1S_TempExplicitName_Success/0.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<Packages xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="../../../../../../../jodi_core/src/main/resources/jodi-packages.v1.1.xsd">

    <Package>
        <FolderCode>BulkLoadORACLE_DWH_STG</FolderCode>
        <PackageName>Trans_1S_TempExplicitName_Success</PackageName>
        <PackageListItem>Trans_1S_TempExplicitName_Success</PackageListItem>
    </Package>

    <Package>
        <PackageName>Trans_1S_TempExplicitName_Success</PackageName>
        <FolderCode>BulkLoadORACLE_DWH_STG</FolderCode>
        <PackageListItem>""</PackageListItem>
        <Before>
            <ExecPackage>
                <Name>Trans_1S_TempExplicitName_Success</Name>
            </ExecPackage>
        </Before>
    </Package>
</Packages>

=== jodi-one/jodi/jodi_qa/src/test/resources/FunctionalTest/xml/Trans_1S_TempDefaultName_Success/0.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<Packages xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../../../../../../jodi_core/src/main/resources/jodi-packages.v1.1.xsd">

	<Package>
		<FolderCode>BulkLoadORACLE_Jodi_STG</FolderCode>
		<PackageName>Trans_1S_TempDefaultName_Success</PackageName>
		<PackageListItem>Trans_1S_TempDefaultName_Success</PackageListItem>
	</Package>

	<Package>
		<PackageName>RUN_ETL_ALL</PackageName>
		<FolderCode>BulkLoadORACLE_Jodi_STG</FolderCode>
		<PackageListItem>""</PackageListItem>
		<Before>
			<ExecPackage>
				<Name>EXAMPLE_ALL</Name>
			</ExecPackage>
		</Before>
	</Package>
</Packages>

=== jodi-one/jodi/jodi_qa/src/test/resources/SampleC/xml/100_DWH_CON_CHINOOK/1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<Packages xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../../../../../../jodi_core/src/main/resources/jodi-packages.v1.1.xsd">
   <Package>
		<PackageName>INSTALL_JOURNAL</PackageName>
		<FolderCode>RealTimeORACLE_DWH_CON_CHINOOK</FolderCode>
		<PackageListItem></PackageListItem>
		<Before>
			<ModelCommand>
				<Name>INSTALL_JOURNAL</Name>
				<Model>model.source.code</Model>
				<ActionType>JOURNALIZE</ActionType>
				<CreateSubscribers>true</CreateSubscribers>
				<InstallJournalization>true</InstallJournalization>
			</ModelCommand>
		</Before>
	</Package>
	<Package>
		<PackageName>UNINSTALL_JOURNAL</PackageName>
		<FolderCode>RealTimeORACLE_DWH_CON_CHINOOK</FolderCode>
		<PackageListItem></PackageListItem>
		<Before>
		  <ModelCommand>
				<Name>UNINSTALL_JOURNAL</Name>
				<Model>model.source.code</Model>
				<ActionType>JOURNALIZE</ActionType>
				<DropSubscribers>true</DropSubscribers>
			</ModelCommand>
			<ModelCommand>
				<Name>UNINSTALL_JOURNAL</Name>
				<Model>model.source.code</Model>
				<ActionType>JOURNALIZE</ActionType>
				<UninstallJournalization>true</UninstallJournalization>
			</ModelCommand>
		</Before>
	</Package>
	<Package>
		<FolderCode>RealTimeORACLE_DWH_CON_CHINOOK</FolderCode>
		<PackageName>REALTIMEDWH_CON_CHINOOK</PackageName>
		<PackageListItem>PACKAGE_ALL</PackageListItem>
		<Before>
			<Variable>
				<Name>LOAD_UP_TO_DATE</Name>
	      <Type>REFRESH</Type>
			</Variable>
		</Before>
	</Package>
</Packages>

=== jodi-one/jodi/jodi_qa/src/test/resources/FunctionalTest/xml/PackageCreation/0.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<Packages xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="../../../../../../../jodi_core/src/main/resources/jodi-packages.v1.1.xsd">

    <Package>
        <FolderCode>BulkLoadORACLE_DWH_STG</FolderCode>
        <PackageName>PACKAGE_CREATION_TEST1</PackageName>
        <PackageListItem>P1</PackageListItem>
        <Failure>
            <Variable>
                <Name>TestVariable3</Name>
                <Type>REFRESH</Type>
            </Variable>
            <Variable>
                <Name>TestVariable2</Name>
                <Type>REFRESH</Type>
            </Variable>
            <Variable>
                <Name>TestVariable1</Name>
                <Type>REFRESH</Type>
            </Variable>
            <Variable>
                <Name>TestVariable1</Name>
                <Type>EVALUATE</Type>
                <Operator>=</Operator>
                <Value>TEST</Value>
            </Variable>
            <ExecProcedure>
                <Name>CREATE_PACKAGE_TEST_PROC</Name>
                <Label>CREATE_PACKAGE_TEST_PROC</Label>
                <Parameters>
                    <Parameter>
                        <Name>Option1</Name>
                        <Value>Option value from XML</Value>
                    </Parameter>
                </Parameters>
            </ExecProcedure>
        </Failure>
    </Package>

    <Package>
        <FolderCode>BulkLoadORACLE_DWH_STG</FolderCode>
        <PackageName>PACKAGE_CREATION_TEST3</PackageName>
        <PackageListItem>P3</PackageListItem>
    </Package>

    <Package>
        <FolderCode>BulkLoadORACLE_DWH_STG</FolderCode>
        <PackageName>PACKAGE_CREATION_TEST2</PackageName>
        <PackageListItem>P2</PackageListItem>
        <Before>
            <Variable>
                <Name>TestVariable2</Name>
                <Type>REFRESH</Type>
            </Variable>
        </Before>
        <After>
            <Variable>
                <Name>TestVariable3</Name>
                <Type>REFRESH</Type>
            </Variable>
        </After>
    </Package>

    <Package>
        <FolderCode>BulkLoadORACLE_DWH_STG</FolderCode>
        <PackageName>PACKAGE_CREATION_TEST_ORCHESTRATION</PackageName>
        <PackageListItem></PackageListItem>
        <Before>
            <ExecCommand>
                <Name>OdiSleep</Name>
                <Label>OdiSleep_Label</Label>
                <Parameters>
                    <Parameter>
                        <Name>DELAY</Name>
                        <Value>1234</Value>
                    </Parameter>
                </Parameters>
            </ExecCommand>
            <ExecCommand>
                <Name>OdiWaitForLogData</Name>
                <Label>OdiWaitForLogData_Label</Label>
                <Parameters>
                    <Parameter>
                        <Name>LSCHEMA</Name>
                        <Value>LSCHEMA</Value>
                    </Parameter>
                    <Parameter>
                        <Name>TABLE_NAME</Name>
                        <Value>TABLE_NAME</Value>
                    </Parameter>
                    <Parameter>
                        <Name>GLOBAL_ROWCOUNT</Name>
                        <Value>1</Value>
                    </Parameter>
                    <Parameter>
                        <Name>OPTIMIZED_WAIT</Name>
                        <Value>AUTO</Value>
                    </Parameter>
                    <Parameter>
                        <Name>POLLINT</Name>
                        <Value>1000</Value>
                    </Parameter>
                    <Parameter>
                        <Name>SUBSCRIBER_NAME</Name>
                        <Value>SUNOPSIS</Value>
                    </Parameter>
                </Parameters>
            </ExecCommand>
            <ExecProcedure>
                <Name>CREATE_PACKAGE_TEST_PROC</Name>
                <Label>CREATE_PACKAGE_TEST_PROC</Label>
                <Parameters>
                    <Parameter>
                        <Name>Option1</Name>
                        <Value>Option value from XML</Value>
                    </Parameter>
                </Parameters>
            </ExecProcedure>
            <ExecPackage>
                <Name>PACKAGE_CREATION_TEST1</Name>
            </ExecPackage>
            <ExecPackage>
                <Name>PACKAGE_CREATION_TEST2</Name>
            </ExecPackage>
            <ExecPackage>
                <Name>PACKAGE_CREATION_TEST3</Name>
                <Asynchronous>true</Asynchronous>
            </ExecPackage>
        </Before>
        <After>
            <Variable>
                <Name>TestVariable2</Name>
                <Type>REFRESH</Type>
            </Variable>
            <Variable>
                <Name>TestVariable3</Name>
                <Type>REFRESH</Type>
            </Variable>
            <Variable>
                <Name>TestVariable1</Name>
                <Type>EVALUATE</Type>
                <Operator>></Operator>
                <Value>TEST</Value>
            </Variable>
            <Variable>
                <Name>TestVariable1</Name>
                <Label>TestVariable1_label</Label>
                <Type>SET</Type>
                <SetOperator>ASSIGN</SetOperator>
                <Value>TEST</Value>
            </Variable>
            <Variable>
                <Name>TestVariable4</Name>
                <Type>SET</Type>
                <SetOperator>INCREMENT</SetOperator>
                <IncrementBy>5</IncrementBy>
            </Variable>
        </After>
        <GotoOnFinalSuccess>CREATE_PACKAGE_TEST_PROC</GotoOnFinalSuccess>
    </Package>

</Packages>
